Fix multisearch query struct
ONSdigital/dp-search-api pull request #113
Opened 2022-05-16 15:45 UTC by rahulPalliyalil

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2022-05-17 08:50 UTC, nshumoogum requested changes
I turned on ES710 flag in component tests and this results in several test failures; we should extend the component tests for ES710.

So run the same features with two separate configurations ES710 flag switched on (true) and the other where this flag is switched off (false)

2022-05-17 08:50 UTC, nshumoogum commented on query/search.go
> +		AggregationField: "type",
By changing this does it not result in an issue with the API interacting with ES 2.2?

2022-05-17 08:50 UTC, nshumoogum commented on query/search_test.go
> +		So(queryString, ShouldContainSubstring, "AggregationField=type")
This should have never changed

2022-05-17 09:49 UTC, rahulPalliyalil commented
> I turned on ES710 flag in component tests and this results in several test failures; we should extend the component tests for ES710.
> 
> So run the same features with two separate configurations ES710 flag switched on (true) and the other where this flag is switched off (false)

As mentioned during standup, will activate the component tests after fixing the transform completely, which will be the next pr. I will extend the current ticket to include the transform fix if its alright ?

2022-05-18 11:41 UTC, nshumoogum approved these changes

2022-05-18 14:11 UTC, merged