Add missing survey and language release calander fields
ONSdigital/dp-search-api pull request #125
Opened 2022-06-21 15:16 UTC by rahulPalliyalil

### What

Add missing survey and language release calander fields

### How to review

Check if the changes make sense

### Who can review

Anyone except me

2022-06-21 15:25 UTC, justinpjose approved these changes

2022-06-21 15:25 UTC, justinpjose requested changes
Just realised that there was an audit failure

2022-06-21 15:49 UTC, rahulPalliyalil commented
> Just realised that there was an audit failure

@justinpjose fixed the audit now . (had to put this in nancy ignore temporarily, as it is not related to my changes).Will need to look into each of the vulnerabilities separately.

2022-06-22 08:40 UTC, justinpjose approved these changes

2022-06-22 16:15 UTC, merged