WIP: Add component tests for filtering by topics
ONSdigital/dp-search-api pull request #173
Opened 2022-11-28 15:15 UTC by RMPall

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2022-12-06 14:52 UTC, nshumoogum requested changes

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple sub topics I get multiple docs
```suggestion
    Scenario: When filtering search results with multiple valid topics, I get multiple docs returned. Both documents have at least one value in "topics" matching 1 of the topic filters
```

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple canonical topics I get multiple docs
```suggestion
    Scenario: When filtering search results with multiple valid topics, I get multiple docs returned. Both documents "canonical_topic" matching 1 of the topic filters
```

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for single canonical topic I get single doc
```suggestion
    Scenario: When filtering search results with a single valid topic, I only get docs returned that have "canonical_topic" field matching the topic filter
```

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for single sub topic I get single doc
```suggestion
    Scenario: When filtering search results with a single valid topic, I only get docs returned that contain a value in "topics" field matching the topic filter
```

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple canonical topics, one that exists and another that does not exist I get single doc
```suggestion
    Scenario: When filtering search results with multiple topics, 1 invalid and 1 valid topic. I only get docs returned that have "canonical_topic" field matching the valid topic filter
```

2022-12-06 14:52 UTC, nshumoogum commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple sub topics, one that exists and another that does not exist I get single doc
```suggestion
    Scenario: When filtering search results with multiple topics, 1 invalid and 1 valid topic. I only get docs returned that contain a value in "topics" field matching the valid topic filter
```

2022-12-08 18:07 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for a canonical topic and a sub topic topics I get multiple docs
Fixed in update 1.

2022-12-08 18:08 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple sub topics I get multiple docs
Fixed in update 1.

2022-12-08 18:08 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple canonical topics I get multiple docs
Fixed in update 1.

2022-12-08 18:10 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for single canonical topic I get single doc
Fixed in update 1.

2022-12-08 18:10 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for single sub topic I get single doc
Fixed in update 1.

2022-12-08 18:11 UTC, RMPall commented on features/search-with-topics.feature
> +    Scenario: When Searching for multiple sub topics, one that exists and another that does not exist I get single doc
Fixed in update 1.

2022-12-08 18:59 UTC, nshumoogum approved these changes

2022-12-12 16:05 UTC, merged