Feature/highlight search results
ONSdigital/dp-search-api pull request #53
Opened 2021-08-19 14:42 UTC by NoelleDL

### What

- removed code the generated snippets with start/end points
- removed bold (`<strong>`) and reverted to default highlighting (`<em>`) in elasticsearch
- updated swagger spec to reflect that MatchDetails no longer exists

### How to review

Check that tests pass, relevant code has been removed and swagger spec is correct. 

### Who can review

Anyone but me.

2021-08-20 11:24 UTC, armstrongb requested changes
To match the design system highlighting.

2021-08-20 11:24 UTC, armstrongb commented on transformer/testdata/search_example.json
> +                                "<em>Housing</em>"
`<em class="highlight">` is the class used in the design system (https://ons-design-system.netlify.app/patterns/see-important-information/)

2021-08-24 10:36 UTC, bpathak-ons reviewed
Appropriate unit tests, with more not-null values, should be added/updated in view of significant changes in slice algorithm in code. Pls don't merge without adding more unit tests and if possible, with regression testing for this branch.

2021-09-07 08:59 UTC, bpathak-ons approved these changes
looks ok to me

2021-09-07 13:43 UTC, armstrongb approved these changes
LGTM - from an examination of the code it looks like highlight class has been added where relevant.

2021-09-07 13:48 UTC, merged